### PR TITLE
#162633465 Implements rating articles

### PR DESCRIPTION
**Pull request by Qadriyah**
**What does this PR do?**
Implements rating articles

**Description of Task to be completed?**

- Create RateArticle component
- Create AverageRating component
- Implement SET_RATE action

**How should this be manually tested?**

- Login into the application
- Select the article that you would like to rate
- Click on the star symbol to rate the article
- The number of rating corresponds to the position of the star symbol

**Any background context you want to provide?**

**What are the relevant pivotal tracker stories?**

[#162633465]('https://www.pivotaltracker.com/n/projects/2231917/stories/162633465')

### CODE REVIEW

**Comment by ruganda** [comment]
good work, @Qadriyah, please resolve the conflicts

**Comment by mubstimor** [comment]
LGTM

**Comment by NabunyaLilian** [comment]
LGTM

**Comment by jeanjoe** [comment]
LGTM

**Pull request merged**
