### PR TITLE
#163899109 Create a PR template file

### PR DESCRIPTION
**Pull request by fatukunda**
**What does this PR do?**

Creates a PR template.

**Description of Task to be completed?**

- After clicking on `create pull request` on github, this template will appear.
- Fill out the descriptions with your own.

**How should this be manually tested?**

- Create a PR on github and this template will show up.

**What are the relevant pivotal tracker stories?**

[#163899109](https://www.pivotaltracker.com/story/show/163899109)

### CODE REVIEW

**Comment by jeanjoe** [comment]
Please update your PR title with the story ID

**Comment by mycok** [comment]
LGTM

**Comment by jeanjoe** [comment]
LGTM

**Comment by mubstimor** [comment]
LGTM

**Pull request merged**
