### PR TITLE
#162633475 Add Search functionality to article list

### PR DESCRIPTION
**Pull request by jeanjoe**
**What does this PR do?**

Search article list basing on user text

**Description of Task to be completed?**

* Add search functionality
* Add tests

**How should this be manually tested?**

- Run `npm install` & `npm start` to run the application.
- Check your redux dev tools to confirm that the state in your app appears in the dev tools.

**Any background context you want to provide?**

- For redux to work with react, remember to install react-redux by running `npm install react-redux`.

**What are the relevant pivotal tracker stories?**

[#162633475](https://www.pivotaltracker.com/n/projects/2231917/stories/162633475)

### CODE REVIEW

**Comment by mubstimor** [comment]
Resolve conflicts first please, otherwise LGTM

**Review by mubstimor — COMMENTED** [review]
please update the commit message accordingly

**Comment by NabunyaLilian** [comment]
LGTM

**Comment by fatukunda** [comment]
LGTM

**Comment by ruganda** [comment]
@jeanjoe Please change your Pr title to follow conventions.

**Pull request merged**
