### PR TITLE
#162633455 Set up react router 4

### PR DESCRIPTION
**Pull request by Qadriyah**
**What does this PR do?**

Setup the react router

**Description of Task to be completed?**

- Install react-router-dom
- Update `webpack.config.js` to add support for page reloading
- Create sample components to demonstrate routing
- Create sample navigation bar
- Update `App.js` to add some routes and a navigation bar

**How should this be manually tested?**

- Run the following commands
`git clone https://github.com/andela/ah-frontend-valkyrie.git`
`yarn start`
- Navigate through pages from the navigation menu

**Any background context you want to provide?**

- None

**What are the relevant pivotal tracker stories?**

[#162633452](https://www.pivotaltracker.com/n/projects/2231917/stories/162633455)

### CODE REVIEW

**Comment by araaliFarooq** [comment]
Do something about that Hound boy otherwise this LGTM.

**Comment by mubstimor** [comment]
please address these hound violations first

**Comment by mubstimor** [comment]
LGTM

**Comment by jeanjoe** [comment]
Please update your PR description to first install your new modules before `yarn start`.

**Comment by NabunyaLilian** [comment]
Please work on hound first.

**Comment by mycok** [comment]
LGTM

**Comment by fatukunda** [comment]
LGTM

**Comment by mubstimor** [comment]
LGTM

**Comment by NabunyaLilian** [comment]
@Qadriyah , please get time and work on the violations.

**Pull request merged**
