### PR TITLE
#162633461 Implements Social Authentication

### PR DESCRIPTION
**Pull request by Qadriyah**
**What does this PR do?**

Implements social authentication

**Description of Task to be completed?**

- Facebook Login
- Google Login
- Attach token to every request after successful login
- Redirect to the landing page
- Prevent authenticated users from accessing the login page
- Update application state with loggedin user data
- Redirect unauthenticated users from to the landing page

**How should this be manually tested?**

- Run `npm start` to run the application.
- Navigate to the login page
- Click on the social media buttons

**Any background context you want to provide?**

- Install dependencies, run `npm install`

**What are the relevant pivotal tracker stories?**

[#162633461](https://www.pivotaltracker.com/n/projects/2231917/stories/162633461)

### CODE REVIEW

**Comment by fatukunda** [comment]
@Qadriyah You commit message shows that you're implementing twitter login and yet you are not. Please rectify that.

**Comment by araaliFarooq** [comment]
45 violations are too many to be ignored. Work on that and fix codeclimate's complaints as well.

**Comment by Qadriyah** [comment]
> 45 violations are too many to be ignored. Work on that and fix codeclimate's complaints as well.

Thank you for the feedback, I would suggest you go through the violations and see exactly what hound is complaining about. However, codeclimate issues have been fixed.

**Comment by fatukunda** [comment]
Apart from the Hound issues. The functionality meets the requirements.
LGTM

**Comment by ruganda** [comment]
Please set up the linter locally, to help you avoid these Hound issues. @Qadriyah

**Comment by NabunyaLilian** [comment]
Hey @Qadriyah , please work on the commit title and also resolve hound violations.

**Comment by NabunyaLilian** [comment]
LGTM

**Pull request merged**
