### PR TITLE
#162633463 Implements view and edit profiles

### PR DESCRIPTION
**Pull request by mubstimor**
**What does this PR do?**

Enable user to view and edit their profiles.

**Description of Task to be completed?**

- Add user profile layout

**How should this be manually tested?**

- Login and click my profile from the user avatar in the top right corner

**What are the relevant pivotal tracker stories?**

[#162633463](https://www.pivotaltracker.com/story/show/162633463)

**Screenshots**
- View profile
screen shot 2019-02-25 at 3 05 02 pm

- Edit Profile
screen shot 2019-02-25 at 3 05 14 pm

### CODE REVIEW

**Comment by araaliFarooq** [comment]
I wouldn't expect you to be having these many hound violations. Please fix them and work on codeclimate as well.

**Comment by fatukunda** [comment]
@mubstimor Good work with the UI design but there is still 14 code climate issues which need to be fixed. Also in the functionality, when the user updates their profile and clicks update, the user information on the sidebar is not automatically updated. The user has to first refresh to see their updated info which I think is not a good user experience.

**Comment by NabunyaLilian** [comment]
Hey @mubstimor, please work on the PR title by removing the FT, make the title descriptive enough and add a # on the PT ID.

**Comment by mubstimor** [comment]
> Hey @mubstimor, please work on the PR title by removing the FT, make the title descriptive enough and add a # on the PT ID.

this has been addressed, thank you.

**Pull request merged**
