### PR TITLE
#162633458 Implement user registration 

### PR DESCRIPTION
**Pull request by araaliFarooq**
**What does this PR do?**

Implements user registration feature.

**Description of Task to be completed?**

* Design an easy to use form for users to enter their details to create accounts.

**How should this be manually tested?**

* Clone the code from github.
* Run ` npm install` or `yarn install` to install dependencies.
* Run ` npm test` or `yarn test` to run tests.
* Run ` npm run build` or `yarn build` to build the app.
* Run `npm start` or `yarn start`  to run the application.
* View output in browser.

**What are the relevant pivotal tracker stories?**

[#162633458](https://www.pivotaltracker.com/story/show/162633458)

### CODE REVIEW

**Comment by fatukunda** [comment]
Well laid out form but could you please pay attention to the following:

- Leaving space between the errors and the textfield would make it look much better
- Consider using signup with instead of just using 'OR' with the social media buttons.
- The confirm email doesn't work. A user is registered even with a non-matching password.
- The register form should not be accessed once the user is logged in.

**Comment by mubstimor** [comment]
Some hound violations are too easy to be ignored, please address them, And for a few issues @fatukunda has raised. Otherwise, LGTM.

**Comment by NabunyaLilian** [comment]
LGTM but please resolve the hound violations.

**Comment by ruganda** [comment]
Please change the format of the relevant PT task in your Pr description to follow the engineering playbook conventions. @araaliFarooq

**Pull request merged**
