### PR TITLE
#162633454 Integrate repo to CI services

### PR DESCRIPTION
**Pull request by mubstimor**
### What this PR does?
- Integrates the repo with Continuous Integration(CI) services like travis, hound and codeclimate

#### Tasks to be completed
- add houndci
- add travis
- add coverage
- update readme file with badges

#### Relevant PT stories
[#162633449](https://www.pivotaltracker.com/story/show/162633449)
[#162633454](https://www.pivotaltracker.com/story/show/162633454)
[#162633457](https://www.pivotaltracker.com/story/show/162633457)

### CODE REVIEW

**Comment by araaliFarooq** [comment]
LGTM

**Comment by fatukunda** [comment]
@mubstimor  You seem to have 2 conflicting files.

**Comment by mubstimor** [comment]
> @mubstimor You seem to have 2 conflicting files.

resolved

**Comment by fatukunda** [comment]
LGTM

**Comment by jeanjoe** [comment]
LGTM

**Pull request merged**
